### ISSUE TITLE
[Feature Request] Allow token holders to list their tokens as retired

### ISSUE THREAD

**Issue by Valareos** [signum-network/signum-explorer#41]
I noticed that certain coins are marked as "potential scam"

Extending this feature to allow token holders to list a token as retired may be a great idea and can be made via a message to an address.

They can set a token as retired, with info on the token retirement.

BTFGPOOL, for example, is merging with BTFGCAKE, and will soon stop paying dividends. Having a retire menu message can key others know what is happening if they thinking on buying the token

Such an option may also be used to update info displayed for a token, bypassing Blockchain listed info

**Comment by pir8radio** [comment]
"potential scam" markings is just a common curtesy for people new to the blockchain.   and since anyone can make an explorer of any kind on their own and not include this,  i think your feature should be a part of the blockchain itself.   like minting more coins they can retire them as well.   just my 2 cents.   Think of the wallets, where you look to see your balance.. they do not get their info from the explorer, they get it from the blockchain directly, so they would not show the retired status..   only the explorer would.

**Comment by pir8radio** [comment]
I think we can close this feature request?
